import TeamGrid from '@/components/TeamGrid';

export default function AboutPage() {
      const adminTeam = [
    { name: 'Regina Jonker', imageUrl: '/staff/regina.jpg' },
    { name: 'Aaron Crossley', imageUrl: '/staff/aaron.jpg' },
    { name: 'Sharon Vaughn', imageUrl: '/staff/sharonv.jpg' },
    { name: 'Ladan Delpak', imageUrl: '/staff/ladan.jpg' },
    { name: 'Sharon Nesbit Davis', imageUrl: '/staff/sharonn.jpg' },
    { name: 'Susan Crossley', imageUrl: '/staff/susanc.jpg' },
  ];

  const boardMembers = [
    { name: 'Susan Spaulding Burke', imageUrl: '/staff/susanb.jpg' },
    { name: 'Romy Rahmanian', imageUrl: '/staff/romy.jpg' },
    { name: 'Sue St. Clair', imageUrl: '/staff/sue.jpg' },
    { name: 'Raven Deerwater', imageUrl: '/staff/raven.jpg' },
    { name: 'Karen Streets Anderson', imageUrl: '/staff/karen.jpg' },
    { name: 'Gary Littell', imageUrl: '/staff/garyl.jpg' },
    { name: 'Gary Sulski', imageUrl: '/staff/garys.jpg' },
  ];

const adminDescriptions = [
    ["Regina grew up in Hamden, Connecticut, where she first consciously embraced social justice in elementary school. She received a BA in Latin American Studies from Stanford University, and an MA in Applied Linguistics from the University of Surrey, UK. She was inducted into the National Spanish Honor Society and later awarded a National Defense Foreign Language Fellowship to study Portuguese. She has worked as a curriculum developer and manager of a language school, an Academic English as a Second Language and Spanish instructor, and translator and interpreter in North America, Europe, and Asia.", "Her professional background in race equity work includes team experience as a program, training and workshop developer for NGOs in San Antonio, Texas and at Columbia University, whose role was to assist public school districts to achieve compliance with US desegregation and bilingual education statutes. Most recently she collaborated on evaluating and editing an anti-racism tool for use by civic, religious, law enforcement and educational organizations across the Province of British Columbia, Canada.", "For nearly a decade Regina facilitated and trained facilitators for English Corner, a weekly space for meaningful conversations in English among immigrants and visiting ESL students. Its purpose is to build community and the capacity to contribute to the betterment of the world. She has since shifted her focus to the development of the Copper to Gold program. As a member of the Bahá’í communities of the United States and Canada, her service on agencies and institutions at the local, regional, and national levels has enhanced the skills she brings to Copper to Gold.", "Regina has broad international and cross-cultural interests in history, reading, ethnomusicology, and dance. She is a musician, has written a few songs and poems along the way, and aspires to nurture a love for justice, critical thinking, beauty, sound, color and humanity in her grandson."],
    ["Raised in a diverse environment, I have always been profoundly influenced by the rich tapestry of cultural experiences surrounding me. However, it took time for me to realize how my identity as a white male had inadvertently shielded me from certain aspects of reality. Through my ongoing journey, I have worked to remove these veils of disconnection, cultivating a more integrated and harmonious relationship with my environment.", "My professional background is varied, encompassing roles in international relations, banking, youth counseling for adjudicated youth, behavioral intervention at a psychiatric residential treatment facility, and production design in the film industry. However, the most significant growth and learning opportunities arose from the relationships I developed, which guided my personal development and introspection.", "As a collaborator in building Copper to Gold, and examining the behaviors associated with racism and prejudice within white communities, this experience has allowed me to better understand the importance of fostering a diverse community, dedicated to unveiling a more comprehensive and accurate depiction of reality."],
    ["As a retired mathematics and computer science educator, technology advocate, and lifelong champion for equity and inclusion, Sharon brings decades of experience in breaking down barriers and empowering others to reach their full potential. Her passion for helping others, combined with her commitment to fostering racial harmony and ending racism, drives her continued involvement in meaningful community work.", "Throughout her career, Sharon combined her passion for education with her love of technology by serving on her school district’s technology team, chairing the county technology committee, and later collaborating with the community college and local businesses to bring vital technology resources into the schools. Technology has been Sharon’s specialty and a tool for change. She not only integrated technology into the classroom but also trained adults to navigate and leverage it in their professional and personal lives. As one of the few Black women in mathematics working alongside predominantly white male colleagues, she overcame significant obstacles while paving the way for others who would follow.", "Beyond her professional achievements, Sharon has enriched her community through diverse service. As a retired Tai Chi and Qigong instructor, she promoted wellness and mindfulness practices. Her experience as a motivational speaker has inspired countless individuals to pursue their goals despite challenges. She has volunteered with activities programs in nursing homes, bringing joy and engagement to elderly residents. Everything she does comes back to that same core belief—we all have something valuable to contribute, and her desire is to help people discover and share their gifts.", "Sharon remains passionate about working toward racial harmony and the elimination of racism. She believes in the transformative power of kindness, mentorship, and education. When not volunteering or advocating for social justice, she enjoys crocheting, exploring interior design, and finding creative ways to make every space she touches more beautiful and welcoming."],
    ["Sharon Nesbit-Davis’s work life has been primarily in the arts. Initially, she was a mimeartist, performing her one-woman show in theaters, schools, and festivals. She bartered tuition for her two children with a private arts alternative school to become an artist in residence and worked with teachers and students to create arts lessons and experiences to enhance curriculum. That work morphed into being accepted onto the roster of artists for the Illinois Arts Council Artist-in-Education program. And that lead to her work with the Rockford Area Arts Council whose dedicated mission was to make the arts accessible for everyone. Through this work, Sharon witnessed people from diverse cultures and backgrounds learn, share, create art, and form genuine friendships. ", "Sharon retired as Executive Director of the Rockford Area Arts Council in 2020 and shifted her artistic focus to writing. Her memoir, Intended, A marriage in Black &amp; White, was published in 2021. Currently she is writing a fictional  (magical realism) book that explores the multi-generational impact of racism on the oppressor. ", "Sharon facilitates “Rebel Writers” classes to encourage courageous and authentic expression, and conducts creative recharge retreats, incorporating storytelling, visual arts, writing, movement, and meditation. She also offers workshops in legacy memoir and spiritual journeying.", "When Sharon was fifteen, a Franciscan Brother took her to the Baha’i Temple in Wilmette and suggested this could be a religion she would like. That turned out to be true. And now, several decades later, she moved with her husband, George, to Evanston, IL for him serve at the Temple.", "George and Sharon married in 1976, have two children and eight grandchildren. Each one unique, and each one contributing to the betterment of the world.", "Concerning Copper to Gold, Sharon says, In 1969 black Civil Rights activist, Julian Bond, was invited to speak at my high school.", "When he finished I rushed to the stage, got in line to meet him and asked, “What can I do to help?” He said what I did not want to hear. “Talk to your people.” I told him I’ve tried, but they won’t listen. He almost smiled. “If you are serious about this work, you’ll keep trying.”", "His words stuck in my head and my heart. I kept trying and the more I did, the less confident I felt in how to do this work. Especially how to confront and eradicate my own racism. Finding Copper to Gold was literally, an answer to prayer."],
    ["I immigrated to United States from Iran at the age of 14 when my father did his Pathology residency in U.S. He firmly believed that his two daughters would not be afforded opportunities in the Patriarchal society of Iran where women are considered lesser than men .My parents made education a high priority in my life. After graduating from the University of Massachusetts, Amherst with a degree in Computer Science, I returned to Florida and started a family.", "My area of interest and experience has always been service whether in form of volunteering at my children’s school as treasurer of the PTA and my local faith community as teacher for the spiritual education of children. My studies and experiences in learning how a community works in a divided society, have made me keenly aware of issues that arise in a privileged homogenous community as contrasted to violence against the black community. Ever-present inequity has prompted me to align with others who are passionate about creating a new model for hum an interaction and organization-one that is based on truth, justice and freedom from racism. ", "My early experiences as an immigrant in the US was welcoming because my family had money, we were educated and we looked white enough. The guiding principle In my life is the Oneness of Humanity. To that end, I strive to see every human being as a contributor to this oneness. I am excited to be apart of Copper to Gold, a program that translates the vision of oneness into a practical and transformative process."],
    ["Susan holds a Doctorate in Organizational Leadership and a Master's in Psychology, with over 45 years of mental health experience. She is a Board Certified Behavior Analyst and a Fellow with the Association of Music & Imagery. Although retired, Susan continues to provide clinical supervision and volunteers at a homeless facility, where she conducts a class called \"Keeping it Real.\"", "Throughout her career, Susan has taught various psychology courses at numerous colleges and universities, emphasizing diversity in her teaching philosophy. She was selected to teach at a Study Abroad Program in Milan, Italy. Susan's background spans grassroots to administration at local, regional, and statewide levels, and she has provided individual, family, and group therapies. She has secured funding for mental health programs targeting families and differently-abled populations through her grant writing.", "Susan's skills as a networker, trainer, public speaker, and workshop presenter have benefited various organizations and sectors. She was a trainer for the Healing Racism curriculum authored by Rita Starr and was contracted with local colleges, governmental institutions and community organizations. Susan has been interviewed on TV, radio, and in newspaper articles. Her work in child assault prevention and service in the area of abused and missing children has earned her recognition from the State of NJ.", "As Assistant Director of International Business Programs at Tennessee State University, Susan directed the Minor in International Business and advised students. She initiated the Multicultural Friendship Society to help international students feel more included, and the group remains active.", "As a consultant and trainer, Susan has tackled topics such as racial amity, diversity, stress management, leadership, team building, Applied Behavior Analysis, Positive Psychology, Autism Spectrum Disorders, ethics, communication skills, bullying, social skills, goal setting, and career development.", "A Baha'i Faith member for 46 years, Susan's personal spiritual growth and commitment to service continue to be a lifelong process. Copper to Gold has opened the door to centering on racial justice and unity, America's most pressing and challenging issue."],
  ];

const boardDescriptions = [
    ["Susan Spaulding Burke brings over three decades of management experience across diverse industries, having held leadership positions with Gannett Co., Inc., Verizon Communications, Inc., and Westinghouse Nuclear. She retired from Westinghouse as a project manager overseeing operating procedures for AP1000 Nuclear Power Plants, where she applied her expertise in professional leadership and training development.", "A lifelong learner committed to bridging understanding across communities, Susan became a tutor with Copper-to-Gold after participating in the program, inspired by insights gained about cross-racial interactions. She has been a devoted member of the Bahá’í faith since 1987, serving the Pittsburgh, PA Cluster in various capacities including the Spiritual Assembly, Area Teaching Committee, and as an educator using Core Curriculum and Ruhi Institute materials. As a Ruhi Institute tutor since the 1990s, she has dedicated herself to spiritual education and community building.", "Susan holds a Bachelor of Fine Arts in Theatre Arts and a Master of Science in Professional Leadership, Training and Development. A Jacksonville, Florida native and proud member of Alpha Kappa Alpha Sorority, she continues her service through volunteering at Crossroads Presbyterian Church Food Pantry and previously served on the board of Evolve Coaching, a nonprofit supporting neurodiverse adults in work and college transitions. She treasures her roles as wife and mother to an adult son, drawing from all her experiences to contribute meaningfully to her community."],
    ["Romy Rahmanian is the principal attorney at the Law Office of Romy S. Rahmanian, a law firm that is dedicated to assisting clients in the areas of estate planning, trust administration, estate litigation, probate, real estate and business law. His work includes advising clients on how to strategically position themselves before litigation becomes necessary. ", "He is an adjunct professor of law at U.C. Berkeley School of Law, University of the Pacific McGeorge School of Law and Southwestern Law School. Romy received his Juris Doctorate Degree from Southwestern Law School where he served as a Senior Editor for the Southwestern Law Review and as a full-time judicial extern for the Honorable Alex Kozinski, Chief Judge of the Ninth Circuit Court of Appeals. He is a member of the California Bar, the Los Angeles County Bar Association and the Sacramento County Bar Association. Romy has also worked as a volunteer for the Bet Tzedek, a non-profit, public interest law firm providing free legal services for underprivileged, elderly and disabled residents in Los Angeles County."],
    ["Sue ‘s professional career in nursing has allowed her to serve both within the U.S and internationally.  Her education includes graduate work at Emory University where she won 1998’s Emory University’s School of Public Health Gangarosa Award in International Health and the School of Nursing’s Graduate Innovative Project award. Sue earned a Master’s degree in nursing doubling as a family nurse practitioner and a psychiatric nurse practitioner; while also earning a Master’s degree in International Public Health. ", "She has served in different leadership roles during her career and while serving as the national director of psychiatric nurse practitioners for a company, she was awarded the Outstanding Professional Award in 2010. Although Sue is currently partially retired, she works parttime as a psychiatric nurse practitioner in telepsychiatry. ", "Sue is a Bahá’í and has served the Bahá’í Faith in several different capacities, both on the homefront and as an international pioneer. Her service is always focused on engagement with individuals, faith-based and community organizations in working for the “betterment of the world through pure and goodly deeds” done locally.", "For a number of years, Sue has been focused on racial justice and the importance for people of African descent, “the Pupil of the Eye”, to be in the forefront of work to develop spiritually just and loving communities."],
    ["Dr. Raven Deerwater is a distinguished mathematics educator with a career dedicated to curriculum development, teacher empowerment, and fostering a sense of belonging in academic communities. He holds a PhD in Education and a Master of Arts in Teaching from the University of Chicago, as well as an A.B. in Economics from Harvard University. He is an author of UCSMP Algebra, UCSMP Geometry, and Bridges to Mathematics (4th and 5th grades).", "After retiring as an enrolled agent (tax practitioner) after 30 years, Raven currently works as a Remote Mathematics Teacher Coach at the University of Michigan, implementing “Belonging Centered Instruction” with teachers of underserved students. This work directly addresses the disparities in mathematics education that often stem from racial and socioeconomic factors by collaborating with teachers to create inclusive and equitable learning environments.", "Raven has also developed curriculum for leadership training in professional organizations. He is on the faculty of the National Association of Enrolled Agent’s Schuldiner/Smollan Leadership Academy, and he is the Vice-President of the Melos Institute (which researches professional organizations).", "Raven lives on the Mendocino Coast in California with his wife Rebecca (an experienced Copper to Gold facilitator), and he is Treasurer of the Mendocino Coast Jewish Community.", "Copper to Gold has had a profound impact on how he views leadership, teaching, andcurricular materials."],
    ["Karen Streets-Anderson is the grand-daughter of civil rights activists.  The Civil Rights Museum at Indiana University South Bend commemorates the contributions her grandparents made to integrate and legally address racial discrimination in South Bend, Indiana.  Being mentored by them, and often included in their social justice and anti-racism activities,  profoundly shaped Karen’s identity, values and worldview.  Their example inspired her to become involved in a number of racial justice and race amity organizations (the NAACP, the Institute for the Healing of Racism) as well as create educational workshops on racial bias and institutionalized racism, culminating in her advisory role and participation in Copper to Gold since its inception.", "After graduating from Mount Holyoke College with a degree in Politics (Political Science), Karen launched a career in broadcast television news production.  This included electronic graphics, floor directing during newscasts, operating cameras in the studio and out in the field, and commercial voice-overs.  She eventually moved on from television to advertising, working as a media buyer for an advertising agency.  While there, she closely worked with minority and women-owned businesses in order to devise marketing strategies that would allow them to gain wider recognition and greater reach.", "Karen has served on the Spiritual Assembly of the Baha’i’s of Nashville, Tennessee, the local governing administrative body of the Nashville Bahá’í community, for 30 years.  For many of those years she has either been the Assembly’s Chairperson, Secretary or Recording Secretary.", "Together, Karen and her husband of 36 years, Nolan, have raised 2 sons who have turned out to be talented young men in their own right. Now entering a new chapter in life, Karen is writing a coming of age novel that explores the intersectionality of race, culture, colorism, class and gender as its main characters try to truly connect with others and build community in spite of seemingly insurmountable obstacles.      "],
    ["Gary Littell lives in Goodfield IL and is a Lead Software engineer with 30 years experience working for State Farm Insurance.  He is currently the lead developer on a team that is transitioning omni-channel contact centers for the State Farm Claims department to the Amazon Web Services platform.  Gary has expertise in voice and chat bot design and development utilized for contact center automation.  He has been awarded multiple patents during his career.  Gary excels at seeing the needs of the day as they pertain to individuals, communities, and institutions and designing and leading teams to deliver technical solutions to address these needs.  Gary graduated from Southern Illinois University with a degree in Electrical Engineering.  He also holds a Chartered Financial Consultant (Chfc) and Chartered Life Underwriter designation from the American College.", "Gary is a Bahá’í and has served the Baha’i Faith in several different capacities.  Most recently his service has focused on activities of race amity.  These activities include participating in the Rooting out Racism boot camp for the past year and serving as a facilitator for the Copper to Gold program."],
    ["Gary Sulski is a dedicated advocate for racial equality and a devoted member of the Bahá’í Faith, a religion that emphasizes the oneness of humanity. Born in a large Midwestern city, Gary grew up witnessing the stark divisions of race and class that plagued the region. Inspired by the Bahá’í teachings he encountered in his early twenties; he committed his life to dismantling prejudice and fostering unity. The Bahá’í principle that all people are created equal under God resonated deeply with him, igniting a passion for social justice that has defined his journey.", "For over five decades, Gary has worked tirelessly to combat racial discrimination. He has organized interfaith dialogues, piloted community workshops, and participated in grassroots initiatives to bridge racial divides. Drawing from the Bahá’í emphasis on eliminating all forms of prejudice, he has championed education as a tool for change, often championing love and fellowship among all races. Gary’s efforts extend beyond words; he has marched in movements, supported policy reforms, and mentored youth from marginalized backgrounds. Now in his late sixties, Gary continues his mission, living out the Bahá’í vision of a united world, one act of service at a time."],
  ];

  return (
    <div className="min-h-screen w-full">
      {/* TOP WHITE SECTION */}
      <div className="py-6 md:py-12 px-8">
        <div className="max-w-4xl mx-auto">
          <div className="text-center">
            <h1 className="font-serif pt-6 md:pt-0 text-3xl md:text-5xl text-[#4A3B32] mb-8">
              About Us
            </h1>

            <div className="space-y6 text-left text-[#4A3B32] font-sans text-l md:text-xl leading-relaxed">
 
              <p>
                <span className="font-bold text-[#B7732B]">Copper <span className="font-normal text-[#000000]"> to 
                <span className="font-bold text-[#F7B000]"> Gold </span></span></span> believes that individuals possess the power to transform their internal lives and impact the world around them. Recognizing and addressing behaviors associated with racial prejudice and superiority promotes a healthy community life.
              </p>
              <p>
                Our mission is to empower individuals to influence communities and institutions by promoting racial justice and unity in diversity.
              </p>
              <p>
                We are a Baha'i inspired, non-profit organization dedicated to achieving race amity through personal transformation.
              </p>
            </div>
          </div>
        </div>
      </div>

      {/* MIDDLE ORANGE SECTION - ADMINISTRATIVE TEAM */}
<div>
        <TeamGrid
          title="Copper to Gold Administrative Team"
          members={adminTeam}
          descriptions={adminDescriptions} 
        />
      </div>

      {/* BOTTOM BEIGE SECTION */}
      <div className="">
        <div className="max-w-4xl mx-auto py-16">
          <p className="font-sans px-6 md:px-0 text-m md:text-[18px] text-[#7A5139] leading-relaxed text-left">
            <span className="font-bold text-[#B7732B]">Copper <span className="font-normal text-[#000000]"> to 
                <span className="font-bold text-[#F7B000]"> Gold </span></span></span> is led by a team who are passionate about advancing healthy and just interracial relationships. Our goal is to promote sustainable change through personal behavioral transformation. With diverse experience in training and developing programs and materials, their backgrounds include: working with educational institutions, parent groups, social service organizations, and law enforcement, on issues such as cultural and ethnic diversity and desegregation compliance. Having developed resources on anti-racism by working with individuals, communities, and institutions, this team is dedicated to building a greater understanding of the impact of unconscious behaviors in their interactions with racialized communities.
          </p>
        </div>

 {/* MIDDLE ORANGE SECTION - Gold members TEAM */}
<TeamGrid
        title="Copper to Gold Board Members"
        members={boardMembers}
        descriptions={boardDescriptions}
      />
      </div>
    </div>
  );
}